DECISION-23036 Enhance FX-Fields to include icon and ratio
sapienstech/angular-forms-extension pull request #117
Opened 2020-10-16 09:49 UTC by swatantrajain-sapiens

2020-10-18 12:47 UTC, urielTwito requested changes

2020-10-18 12:47 UTC, urielTwito commented on src/lib/src/component/field.component.ts
> +  @Input() display: string;
I am not sure what are the allowed values are.  the name does not tell me too much.
'block' value is too technical in my opinion

2020-10-18 12:47 UTC, urielTwito commented on src/lib/src/component/field.component.ts
> +enum DisplayType {
these values are too technical, we need something that describes the feature.
like LABEL_ON_TOP/ LABEL_O_LEFT/ LABEL_ON_RIGHT ...

2020-10-18 12:47 UTC, urielTwito commented on src/lib/src/component/field.component.ts
> +         [ngClass]="(this.displayType === 'block')?'fx-field--block':'fx-field--flex'">
I would put here the name of the feature (and in css we can decide what the value is. 
we do not want to write css code in the component,
the component should be abstract to css. just tell what we want and not how to do it.

2020-10-18 12:47 UTC, urielTwito commented on karma-test-shim.js
> +    'rxjs': 'npm:rxjs/index.js',
💯

2020-10-18 12:47 UTC, urielTwito commented on src/demo/systemjs.config.js
> +        main: 'index.js',
👍

2020-10-18 12:47 UTC, urielTwito commented on src/demo/app/app.component.ts
> +      <fx-field [label]="'Name'" class="flex-container align-items-center user-display-name-div-spec" icon="icon-class" display="flex" labelInputWidthPercentage="30">
this looks like css, I explained this above

2020-10-18 13:14 UTC, swatantrajain-sapiens commented on src/lib/src/component/field.component.ts
> +         [ngClass]="(this.displayType === 'block')?'fx-field--block':'fx-field--flex'">
This would only add the class `fx-field--block` or `fx-field--flex` based on the value of the input parameter `display`

The css will be implemented in the NG project which based on the class.

2020-10-18 13:15 UTC, swatantrajain-sapiens commented on src/demo/app/app.component.ts
> +      <fx-field [label]="'Name'" class="flex-container align-items-center user-display-name-div-spec" icon="icon-class" display="flex" labelInputWidthPercentage="30">
This is just the demo project app module and I wanted to add the attributes in the demo app for example.

This is not implementation but just example

2020-10-18 13:17 UTC, swatantrajain-sapiens commented on src/lib/src/component/field.component.ts
> +         [ngClass]="(this.displayType === 'block')?'fx-field--block':'fx-field--flex'">
NG project PR
https://github.com/sapienstech/decision-client-ng2/pull/4200

2020-10-18 13:31 UTC, urielTwito commented on src/demo/app/app.component.ts
> +      <fx-field [label]="'Name'" class="flex-container align-items-center user-display-name-div-spec" icon="icon-class" display="flex" labelInputWidthPercentage="30">
good practice to use attribute that way : [icon]="'icon-class'"

2020-10-19 13:08 UTC, swatantrajain-sapiens commented on src/demo/app/app.component.ts
> +      <fx-field [label]="'Name'" class="flex-container align-items-center user-display-name-div-spec" icon="icon-class" display="flex" labelInputWidthPercentage="30">
Done

2020-10-19 13:09 UTC, swatantrajain-sapiens commented on src/lib/src/component/field.component.ts
> +         [ngClass]="(this.displayType === 'block')?'fx-field--block':'fx-field--flex'">
Changed as per comments.

2020-10-19 13:09 UTC, swatantrajain-sapiens commented on src/lib/src/component/field.component.ts
> +enum DisplayType {
Updated

2020-10-19 13:10 UTC, swatantrajain-sapiens commented on src/lib/src/component/field.component.ts
> +  @Input() display: string;
agreed, removed technical values to fucntional values and added a domain to prevent from errors

2020-10-20 13:33 UTC, urielTwito commented on src/lib/src/component/field.component.ts
> +  @Input() labelRelativePos: "label_on_top" | "label_on_right" | "label_on_bottom" | "label_on_left" = "label_on_left";
we have an enum so we can use it here

2020-10-20 13:36 UTC, urielTwito commented on src/lib/src/component/field.component.ts
> +  private get labelInputRelativeDisplay(): LabelnputRelativeDisplayType {
if we use the enum we probably will not need this transformation

2020-10-20 14:50 UTC, swatantrajain-sapiens commented on src/lib/src/component/field.component.ts
> +  @Input() labelRelativePos: "label_on_top" | "label_on_right" | "label_on_bottom" | "label_on_left" = "label_on_left";
@urielTwito I would need your help to export this enum from field component to outside modules.

2020-10-21 09:16 UTC, urielTwito approved these changes

2020-10-21 09:16 UTC, merged